a1 = input('Digite algo: ')
print('O tipo primitvo desse valor é ', type(a1))
print('Só tem espaços? ', a1.isspace())
print('É um número? ', a1.isnumeric())
print('É alfabético? ', a1.isalpha())
print('É alfanumérico? ', a1.isalnum())
print('Está em maiúsculas? ', a1.isupper())
print('Está em minúsculas? ', a1.islower())
print('Está capitalizada? ', a1.istitle())
